package dremioinstance


type DremioInstanceAuthenticationOauth struct {
	// The Issuer location URI, where the OIDC provider configuration can be found.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.99.0/docs/resources/dremio_instance#authority_url DremioInstance#authority_url}
	AuthorityUrl *string `field:"required" json:"authorityUrl" yaml:"authorityUrl"`
	// The client ID assigned by the Identity Provider.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.99.0/docs/resources/dremio_instance#client_id DremioInstance#client_id}
	ClientId *string `field:"required" json:"clientId" yaml:"clientId"`
	// The client secret generated by the Identity Provider.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.99.0/docs/resources/dremio_instance#client_secret DremioInstance#client_secret}
	ClientSecret *string `field:"required" json:"clientSecret" yaml:"clientSecret"`
	// Maps fields from the JWT token to fields Dremio requires.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.99.0/docs/resources/dremio_instance#jwt_claims DremioInstance#jwt_claims}
	JwtClaims *DremioInstanceAuthenticationOauthJwtClaims `field:"required" json:"jwtClaims" yaml:"jwtClaims"`
	// Any additional parameters the Identity Provider requires.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.99.0/docs/resources/dremio_instance#parameters DremioInstance#parameters}
	Parameters interface{} `field:"optional" json:"parameters" yaml:"parameters"`
	// A list of space-separated scopes. The `openid` scope is always required; other scopes can vary by provider.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.99.0/docs/resources/dremio_instance#scope DremioInstance#scope}
	Scope *string `field:"optional" json:"scope" yaml:"scope"`
}

