package redisinstance

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"stackit.redisInstance.RedisInstance",
		reflect.TypeOf((*RedisInstance)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "cfGuid", GoGetter: "CfGuid"},
			_jsii_.MemberProperty{JsiiProperty: "cfOrganizationGuid", GoGetter: "CfOrganizationGuid"},
			_jsii_.MemberProperty{JsiiProperty: "cfSpaceGuid", GoGetter: "CfSpaceGuid"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dashboardUrl", GoGetter: "DashboardUrl"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "imageUrl", GoGetter: "ImageUrl"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "instanceId", GoGetter: "InstanceId"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "parameters", GoGetter: "Parameters"},
			_jsii_.MemberProperty{JsiiProperty: "parametersInput", GoGetter: "ParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "planId", GoGetter: "PlanId"},
			_jsii_.MemberProperty{JsiiProperty: "planName", GoGetter: "PlanName"},
			_jsii_.MemberProperty{JsiiProperty: "planNameInput", GoGetter: "PlanNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "projectId", GoGetter: "ProjectId"},
			_jsii_.MemberProperty{JsiiProperty: "projectIdInput", GoGetter: "ProjectIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putParameters", GoMethod: "PutParameters"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetParameters", GoMethod: "ResetParameters"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "version", GoGetter: "Version"},
			_jsii_.MemberProperty{JsiiProperty: "versionInput", GoGetter: "VersionInput"},
		},
		func() interface{} {
			j := jsiiProxy_RedisInstance{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.redisInstance.RedisInstanceConfig",
		reflect.TypeOf((*RedisInstanceConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"stackit.redisInstance.RedisInstanceParameters",
		reflect.TypeOf((*RedisInstanceParameters)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.redisInstance.RedisInstanceParametersOutputReference",
		reflect.TypeOf((*RedisInstanceParametersOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "downAfterMilliseconds", GoGetter: "DownAfterMilliseconds"},
			_jsii_.MemberProperty{JsiiProperty: "downAfterMillisecondsInput", GoGetter: "DownAfterMillisecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableMonitoring", GoGetter: "EnableMonitoring"},
			_jsii_.MemberProperty{JsiiProperty: "enableMonitoringInput", GoGetter: "EnableMonitoringInput"},
			_jsii_.MemberProperty{JsiiProperty: "failoverTimeout", GoGetter: "FailoverTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "failoverTimeoutInput", GoGetter: "FailoverTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "graphite", GoGetter: "Graphite"},
			_jsii_.MemberProperty{JsiiProperty: "graphiteInput", GoGetter: "GraphiteInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lazyfreeLazyEviction", GoGetter: "LazyfreeLazyEviction"},
			_jsii_.MemberProperty{JsiiProperty: "lazyfreeLazyEvictionInput", GoGetter: "LazyfreeLazyEvictionInput"},
			_jsii_.MemberProperty{JsiiProperty: "lazyfreeLazyExpire", GoGetter: "LazyfreeLazyExpire"},
			_jsii_.MemberProperty{JsiiProperty: "lazyfreeLazyExpireInput", GoGetter: "LazyfreeLazyExpireInput"},
			_jsii_.MemberProperty{JsiiProperty: "luaTimeLimit", GoGetter: "LuaTimeLimit"},
			_jsii_.MemberProperty{JsiiProperty: "luaTimeLimitInput", GoGetter: "LuaTimeLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxclients", GoGetter: "Maxclients"},
			_jsii_.MemberProperty{JsiiProperty: "maxclientsInput", GoGetter: "MaxclientsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxDiskThreshold", GoGetter: "MaxDiskThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "maxDiskThresholdInput", GoGetter: "MaxDiskThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxmemoryPolicy", GoGetter: "MaxmemoryPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "maxmemoryPolicyInput", GoGetter: "MaxmemoryPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxmemorySamples", GoGetter: "MaxmemorySamples"},
			_jsii_.MemberProperty{JsiiProperty: "maxmemorySamplesInput", GoGetter: "MaxmemorySamplesInput"},
			_jsii_.MemberProperty{JsiiProperty: "metricsFrequency", GoGetter: "MetricsFrequency"},
			_jsii_.MemberProperty{JsiiProperty: "metricsFrequencyInput", GoGetter: "MetricsFrequencyInput"},
			_jsii_.MemberProperty{JsiiProperty: "metricsPrefix", GoGetter: "MetricsPrefix"},
			_jsii_.MemberProperty{JsiiProperty: "metricsPrefixInput", GoGetter: "MetricsPrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "minReplicasMaxLag", GoGetter: "MinReplicasMaxLag"},
			_jsii_.MemberProperty{JsiiProperty: "minReplicasMaxLagInput", GoGetter: "MinReplicasMaxLagInput"},
			_jsii_.MemberProperty{JsiiProperty: "monitoringInstanceId", GoGetter: "MonitoringInstanceId"},
			_jsii_.MemberProperty{JsiiProperty: "monitoringInstanceIdInput", GoGetter: "MonitoringInstanceIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "notifyKeyspaceEvents", GoGetter: "NotifyKeyspaceEvents"},
			_jsii_.MemberProperty{JsiiProperty: "notifyKeyspaceEventsInput", GoGetter: "NotifyKeyspaceEventsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetDownAfterMilliseconds", GoMethod: "ResetDownAfterMilliseconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableMonitoring", GoMethod: "ResetEnableMonitoring"},
			_jsii_.MemberMethod{JsiiMethod: "resetFailoverTimeout", GoMethod: "ResetFailoverTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetGraphite", GoMethod: "ResetGraphite"},
			_jsii_.MemberMethod{JsiiMethod: "resetLazyfreeLazyEviction", GoMethod: "ResetLazyfreeLazyEviction"},
			_jsii_.MemberMethod{JsiiMethod: "resetLazyfreeLazyExpire", GoMethod: "ResetLazyfreeLazyExpire"},
			_jsii_.MemberMethod{JsiiMethod: "resetLuaTimeLimit", GoMethod: "ResetLuaTimeLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxclients", GoMethod: "ResetMaxclients"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxDiskThreshold", GoMethod: "ResetMaxDiskThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxmemoryPolicy", GoMethod: "ResetMaxmemoryPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxmemorySamples", GoMethod: "ResetMaxmemorySamples"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetricsFrequency", GoMethod: "ResetMetricsFrequency"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetricsPrefix", GoMethod: "ResetMetricsPrefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinReplicasMaxLag", GoMethod: "ResetMinReplicasMaxLag"},
			_jsii_.MemberMethod{JsiiMethod: "resetMonitoringInstanceId", GoMethod: "ResetMonitoringInstanceId"},
			_jsii_.MemberMethod{JsiiMethod: "resetNotifyKeyspaceEvents", GoMethod: "ResetNotifyKeyspaceEvents"},
			_jsii_.MemberMethod{JsiiMethod: "resetSgwAcl", GoMethod: "ResetSgwAcl"},
			_jsii_.MemberMethod{JsiiMethod: "resetSnapshot", GoMethod: "ResetSnapshot"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyslog", GoMethod: "ResetSyslog"},
			_jsii_.MemberMethod{JsiiMethod: "resetTlsCiphers", GoMethod: "ResetTlsCiphers"},
			_jsii_.MemberMethod{JsiiMethod: "resetTlsCiphersuites", GoMethod: "ResetTlsCiphersuites"},
			_jsii_.MemberMethod{JsiiMethod: "resetTlsProtocols", GoMethod: "ResetTlsProtocols"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "sgwAcl", GoGetter: "SgwAcl"},
			_jsii_.MemberProperty{JsiiProperty: "sgwAclInput", GoGetter: "SgwAclInput"},
			_jsii_.MemberProperty{JsiiProperty: "snapshot", GoGetter: "Snapshot"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotInput", GoGetter: "SnapshotInput"},
			_jsii_.MemberProperty{JsiiProperty: "syslog", GoGetter: "Syslog"},
			_jsii_.MemberProperty{JsiiProperty: "syslogInput", GoGetter: "SyslogInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "tlsCiphers", GoGetter: "TlsCiphers"},
			_jsii_.MemberProperty{JsiiProperty: "tlsCiphersInput", GoGetter: "TlsCiphersInput"},
			_jsii_.MemberProperty{JsiiProperty: "tlsCiphersuites", GoGetter: "TlsCiphersuites"},
			_jsii_.MemberProperty{JsiiProperty: "tlsCiphersuitesInput", GoGetter: "TlsCiphersuitesInput"},
			_jsii_.MemberProperty{JsiiProperty: "tlsProtocols", GoGetter: "TlsProtocols"},
			_jsii_.MemberProperty{JsiiProperty: "tlsProtocolsInput", GoGetter: "TlsProtocolsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_RedisInstanceParametersOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
