package vpnconnection

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnection",
		reflect.TypeOf((*VpnConnection)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "connectionId", GoGetter: "ConnectionId"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "displayName", GoGetter: "DisplayName"},
			_jsii_.MemberProperty{JsiiProperty: "displayNameInput", GoGetter: "DisplayNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberProperty{JsiiProperty: "gatewayId", GoGetter: "GatewayId"},
			_jsii_.MemberProperty{JsiiProperty: "gatewayIdInput", GoGetter: "GatewayIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "labels", GoGetter: "Labels"},
			_jsii_.MemberProperty{JsiiProperty: "labelsInput", GoGetter: "LabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "localSubnets", GoGetter: "LocalSubnets"},
			_jsii_.MemberProperty{JsiiProperty: "localSubnetsInput", GoGetter: "LocalSubnetsInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "projectId", GoGetter: "ProjectId"},
			_jsii_.MemberProperty{JsiiProperty: "projectIdInput", GoGetter: "ProjectIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putTunnel1", GoMethod: "PutTunnel1"},
			_jsii_.MemberMethod{JsiiMethod: "putTunnel2", GoMethod: "PutTunnel2"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberProperty{JsiiProperty: "regionInput", GoGetter: "RegionInput"},
			_jsii_.MemberProperty{JsiiProperty: "remoteSubnets", GoGetter: "RemoteSubnets"},
			_jsii_.MemberProperty{JsiiProperty: "remoteSubnetsInput", GoGetter: "RemoteSubnetsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetLabels", GoMethod: "ResetLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetLocalSubnets", GoMethod: "ResetLocalSubnets"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRegion", GoMethod: "ResetRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetRemoteSubnets", GoMethod: "ResetRemoteSubnets"},
			_jsii_.MemberMethod{JsiiMethod: "resetStaticRoutes", GoMethod: "ResetStaticRoutes"},
			_jsii_.MemberProperty{JsiiProperty: "staticRoutes", GoGetter: "StaticRoutes"},
			_jsii_.MemberProperty{JsiiProperty: "staticRoutesInput", GoGetter: "StaticRoutesInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "tunnel1", GoGetter: "Tunnel1"},
			_jsii_.MemberProperty{JsiiProperty: "tunnel1Input", GoGetter: "Tunnel1Input"},
			_jsii_.MemberProperty{JsiiProperty: "tunnel2", GoGetter: "Tunnel2"},
			_jsii_.MemberProperty{JsiiProperty: "tunnel2Input", GoGetter: "Tunnel2Input"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnection{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionConfig",
		reflect.TypeOf((*VpnConnectionConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel1",
		reflect.TypeOf((*VpnConnectionTunnel1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel1Bgp",
		reflect.TypeOf((*VpnConnectionTunnel1Bgp)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel1BgpOutputReference",
		reflect.TypeOf((*VpnConnectionTunnel1BgpOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAsn", GoGetter: "RemoteAsn"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAsnInput", GoGetter: "RemoteAsnInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel1BgpOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel1OutputReference",
		reflect.TypeOf((*VpnConnectionTunnel1OutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "bgp", GoGetter: "Bgp"},
			_jsii_.MemberProperty{JsiiProperty: "bgpInput", GoGetter: "BgpInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "peering", GoGetter: "Peering"},
			_jsii_.MemberProperty{JsiiProperty: "peeringInput", GoGetter: "PeeringInput"},
			_jsii_.MemberProperty{JsiiProperty: "phase1", GoGetter: "Phase1"},
			_jsii_.MemberProperty{JsiiProperty: "phase1Input", GoGetter: "Phase1Input"},
			_jsii_.MemberProperty{JsiiProperty: "phase2", GoGetter: "Phase2"},
			_jsii_.MemberProperty{JsiiProperty: "phase2Input", GoGetter: "Phase2Input"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKey", GoGetter: "PreSharedKey"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyInput", GoGetter: "PreSharedKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyWo", GoGetter: "PreSharedKeyWo"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyWoInput", GoGetter: "PreSharedKeyWoInput"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyWoVersion", GoGetter: "PreSharedKeyWoVersion"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyWoVersionInput", GoGetter: "PreSharedKeyWoVersionInput"},
			_jsii_.MemberMethod{JsiiMethod: "putBgp", GoMethod: "PutBgp"},
			_jsii_.MemberMethod{JsiiMethod: "putPeering", GoMethod: "PutPeering"},
			_jsii_.MemberMethod{JsiiMethod: "putPhase1", GoMethod: "PutPhase1"},
			_jsii_.MemberMethod{JsiiMethod: "putPhase2", GoMethod: "PutPhase2"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAddress", GoGetter: "RemoteAddress"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAddressInput", GoGetter: "RemoteAddressInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgp", GoMethod: "ResetBgp"},
			_jsii_.MemberMethod{JsiiMethod: "resetPeering", GoMethod: "ResetPeering"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreSharedKey", GoMethod: "ResetPreSharedKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreSharedKeyWo", GoMethod: "ResetPreSharedKeyWo"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreSharedKeyWoVersion", GoMethod: "ResetPreSharedKeyWoVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel1OutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel1Peering",
		reflect.TypeOf((*VpnConnectionTunnel1Peering)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel1PeeringOutputReference",
		reflect.TypeOf((*VpnConnectionTunnel1PeeringOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "localAddress", GoGetter: "LocalAddress"},
			_jsii_.MemberProperty{JsiiProperty: "localAddressInput", GoGetter: "LocalAddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAddress", GoGetter: "RemoteAddress"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAddressInput", GoGetter: "RemoteAddressInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel1PeeringOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel1Phase1",
		reflect.TypeOf((*VpnConnectionTunnel1Phase1)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel1Phase1OutputReference",
		reflect.TypeOf((*VpnConnectionTunnel1Phase1OutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dhGroups", GoGetter: "DhGroups"},
			_jsii_.MemberProperty{JsiiProperty: "dhGroupsInput", GoGetter: "DhGroupsInput"},
			_jsii_.MemberProperty{JsiiProperty: "encryptionAlgorithms", GoGetter: "EncryptionAlgorithms"},
			_jsii_.MemberProperty{JsiiProperty: "encryptionAlgorithmsInput", GoGetter: "EncryptionAlgorithmsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "integrityAlgorithms", GoGetter: "IntegrityAlgorithms"},
			_jsii_.MemberProperty{JsiiProperty: "integrityAlgorithmsInput", GoGetter: "IntegrityAlgorithmsInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "rekeyTime", GoGetter: "RekeyTime"},
			_jsii_.MemberProperty{JsiiProperty: "rekeyTimeInput", GoGetter: "RekeyTimeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetDhGroups", GoMethod: "ResetDhGroups"},
			_jsii_.MemberMethod{JsiiMethod: "resetRekeyTime", GoMethod: "ResetRekeyTime"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel1Phase1OutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel1Phase2",
		reflect.TypeOf((*VpnConnectionTunnel1Phase2)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel1Phase2OutputReference",
		reflect.TypeOf((*VpnConnectionTunnel1Phase2OutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dhGroups", GoGetter: "DhGroups"},
			_jsii_.MemberProperty{JsiiProperty: "dhGroupsInput", GoGetter: "DhGroupsInput"},
			_jsii_.MemberProperty{JsiiProperty: "dpdAction", GoGetter: "DpdAction"},
			_jsii_.MemberProperty{JsiiProperty: "dpdActionInput", GoGetter: "DpdActionInput"},
			_jsii_.MemberProperty{JsiiProperty: "encryptionAlgorithms", GoGetter: "EncryptionAlgorithms"},
			_jsii_.MemberProperty{JsiiProperty: "encryptionAlgorithmsInput", GoGetter: "EncryptionAlgorithmsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "integrityAlgorithms", GoGetter: "IntegrityAlgorithms"},
			_jsii_.MemberProperty{JsiiProperty: "integrityAlgorithmsInput", GoGetter: "IntegrityAlgorithmsInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "rekeyTime", GoGetter: "RekeyTime"},
			_jsii_.MemberProperty{JsiiProperty: "rekeyTimeInput", GoGetter: "RekeyTimeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetDhGroups", GoMethod: "ResetDhGroups"},
			_jsii_.MemberMethod{JsiiMethod: "resetDpdAction", GoMethod: "ResetDpdAction"},
			_jsii_.MemberMethod{JsiiMethod: "resetRekeyTime", GoMethod: "ResetRekeyTime"},
			_jsii_.MemberMethod{JsiiMethod: "resetStartAction", GoMethod: "ResetStartAction"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "startAction", GoGetter: "StartAction"},
			_jsii_.MemberProperty{JsiiProperty: "startActionInput", GoGetter: "StartActionInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel1Phase2OutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel2",
		reflect.TypeOf((*VpnConnectionTunnel2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel2Bgp",
		reflect.TypeOf((*VpnConnectionTunnel2Bgp)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel2BgpOutputReference",
		reflect.TypeOf((*VpnConnectionTunnel2BgpOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAsn", GoGetter: "RemoteAsn"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAsnInput", GoGetter: "RemoteAsnInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel2BgpOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel2OutputReference",
		reflect.TypeOf((*VpnConnectionTunnel2OutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "bgp", GoGetter: "Bgp"},
			_jsii_.MemberProperty{JsiiProperty: "bgpInput", GoGetter: "BgpInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "peering", GoGetter: "Peering"},
			_jsii_.MemberProperty{JsiiProperty: "peeringInput", GoGetter: "PeeringInput"},
			_jsii_.MemberProperty{JsiiProperty: "phase1", GoGetter: "Phase1"},
			_jsii_.MemberProperty{JsiiProperty: "phase1Input", GoGetter: "Phase1Input"},
			_jsii_.MemberProperty{JsiiProperty: "phase2", GoGetter: "Phase2"},
			_jsii_.MemberProperty{JsiiProperty: "phase2Input", GoGetter: "Phase2Input"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKey", GoGetter: "PreSharedKey"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyInput", GoGetter: "PreSharedKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyWo", GoGetter: "PreSharedKeyWo"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyWoInput", GoGetter: "PreSharedKeyWoInput"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyWoVersion", GoGetter: "PreSharedKeyWoVersion"},
			_jsii_.MemberProperty{JsiiProperty: "preSharedKeyWoVersionInput", GoGetter: "PreSharedKeyWoVersionInput"},
			_jsii_.MemberMethod{JsiiMethod: "putBgp", GoMethod: "PutBgp"},
			_jsii_.MemberMethod{JsiiMethod: "putPeering", GoMethod: "PutPeering"},
			_jsii_.MemberMethod{JsiiMethod: "putPhase1", GoMethod: "PutPhase1"},
			_jsii_.MemberMethod{JsiiMethod: "putPhase2", GoMethod: "PutPhase2"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAddress", GoGetter: "RemoteAddress"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAddressInput", GoGetter: "RemoteAddressInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgp", GoMethod: "ResetBgp"},
			_jsii_.MemberMethod{JsiiMethod: "resetPeering", GoMethod: "ResetPeering"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreSharedKey", GoMethod: "ResetPreSharedKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreSharedKeyWo", GoMethod: "ResetPreSharedKeyWo"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreSharedKeyWoVersion", GoMethod: "ResetPreSharedKeyWoVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel2OutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel2Peering",
		reflect.TypeOf((*VpnConnectionTunnel2Peering)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel2PeeringOutputReference",
		reflect.TypeOf((*VpnConnectionTunnel2PeeringOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "localAddress", GoGetter: "LocalAddress"},
			_jsii_.MemberProperty{JsiiProperty: "localAddressInput", GoGetter: "LocalAddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAddress", GoGetter: "RemoteAddress"},
			_jsii_.MemberProperty{JsiiProperty: "remoteAddressInput", GoGetter: "RemoteAddressInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel2PeeringOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel2Phase1",
		reflect.TypeOf((*VpnConnectionTunnel2Phase1)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel2Phase1OutputReference",
		reflect.TypeOf((*VpnConnectionTunnel2Phase1OutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dhGroups", GoGetter: "DhGroups"},
			_jsii_.MemberProperty{JsiiProperty: "dhGroupsInput", GoGetter: "DhGroupsInput"},
			_jsii_.MemberProperty{JsiiProperty: "encryptionAlgorithms", GoGetter: "EncryptionAlgorithms"},
			_jsii_.MemberProperty{JsiiProperty: "encryptionAlgorithmsInput", GoGetter: "EncryptionAlgorithmsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "integrityAlgorithms", GoGetter: "IntegrityAlgorithms"},
			_jsii_.MemberProperty{JsiiProperty: "integrityAlgorithmsInput", GoGetter: "IntegrityAlgorithmsInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "rekeyTime", GoGetter: "RekeyTime"},
			_jsii_.MemberProperty{JsiiProperty: "rekeyTimeInput", GoGetter: "RekeyTimeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetDhGroups", GoMethod: "ResetDhGroups"},
			_jsii_.MemberMethod{JsiiMethod: "resetRekeyTime", GoMethod: "ResetRekeyTime"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel2Phase1OutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.vpnConnection.VpnConnectionTunnel2Phase2",
		reflect.TypeOf((*VpnConnectionTunnel2Phase2)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.vpnConnection.VpnConnectionTunnel2Phase2OutputReference",
		reflect.TypeOf((*VpnConnectionTunnel2Phase2OutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dhGroups", GoGetter: "DhGroups"},
			_jsii_.MemberProperty{JsiiProperty: "dhGroupsInput", GoGetter: "DhGroupsInput"},
			_jsii_.MemberProperty{JsiiProperty: "dpdAction", GoGetter: "DpdAction"},
			_jsii_.MemberProperty{JsiiProperty: "dpdActionInput", GoGetter: "DpdActionInput"},
			_jsii_.MemberProperty{JsiiProperty: "encryptionAlgorithms", GoGetter: "EncryptionAlgorithms"},
			_jsii_.MemberProperty{JsiiProperty: "encryptionAlgorithmsInput", GoGetter: "EncryptionAlgorithmsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "integrityAlgorithms", GoGetter: "IntegrityAlgorithms"},
			_jsii_.MemberProperty{JsiiProperty: "integrityAlgorithmsInput", GoGetter: "IntegrityAlgorithmsInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "rekeyTime", GoGetter: "RekeyTime"},
			_jsii_.MemberProperty{JsiiProperty: "rekeyTimeInput", GoGetter: "RekeyTimeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetDhGroups", GoMethod: "ResetDhGroups"},
			_jsii_.MemberMethod{JsiiMethod: "resetDpdAction", GoMethod: "ResetDpdAction"},
			_jsii_.MemberMethod{JsiiMethod: "resetRekeyTime", GoMethod: "ResetRekeyTime"},
			_jsii_.MemberMethod{JsiiMethod: "resetStartAction", GoMethod: "ResetStartAction"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "startAction", GoGetter: "StartAction"},
			_jsii_.MemberProperty{JsiiProperty: "startActionInput", GoGetter: "StartActionInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VpnConnectionTunnel2Phase2OutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
