package network

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"stackit.network.Network",
		reflect.TypeOf((*Network)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4Gateway", GoGetter: "Ipv4Gateway"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4GatewayInput", GoGetter: "Ipv4GatewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4Nameservers", GoGetter: "Ipv4Nameservers"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4NameserversInput", GoGetter: "Ipv4NameserversInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4Prefix", GoGetter: "Ipv4Prefix"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4Prefixes", GoGetter: "Ipv4Prefixes"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4PrefixInput", GoGetter: "Ipv4PrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4PrefixLength", GoGetter: "Ipv4PrefixLength"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4PrefixLengthInput", GoGetter: "Ipv4PrefixLengthInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6Gateway", GoGetter: "Ipv6Gateway"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6GatewayInput", GoGetter: "Ipv6GatewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6Nameservers", GoGetter: "Ipv6Nameservers"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6NameserversInput", GoGetter: "Ipv6NameserversInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6Prefix", GoGetter: "Ipv6Prefix"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6Prefixes", GoGetter: "Ipv6Prefixes"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6PrefixInput", GoGetter: "Ipv6PrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6PrefixLength", GoGetter: "Ipv6PrefixLength"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6PrefixLengthInput", GoGetter: "Ipv6PrefixLengthInput"},
			_jsii_.MemberProperty{JsiiProperty: "labels", GoGetter: "Labels"},
			_jsii_.MemberProperty{JsiiProperty: "labelsInput", GoGetter: "LabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "nameservers", GoGetter: "Nameservers"},
			_jsii_.MemberProperty{JsiiProperty: "nameserversInput", GoGetter: "NameserversInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkId", GoGetter: "NetworkId"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "noIpv4Gateway", GoGetter: "NoIpv4Gateway"},
			_jsii_.MemberProperty{JsiiProperty: "noIpv4GatewayInput", GoGetter: "NoIpv4GatewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "noIpv6Gateway", GoGetter: "NoIpv6Gateway"},
			_jsii_.MemberProperty{JsiiProperty: "noIpv6GatewayInput", GoGetter: "NoIpv6GatewayInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "prefixes", GoGetter: "Prefixes"},
			_jsii_.MemberProperty{JsiiProperty: "projectId", GoGetter: "ProjectId"},
			_jsii_.MemberProperty{JsiiProperty: "projectIdInput", GoGetter: "ProjectIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "publicIp", GoGetter: "PublicIp"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberProperty{JsiiProperty: "regionInput", GoGetter: "RegionInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv4Gateway", GoMethod: "ResetIpv4Gateway"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv4Nameservers", GoMethod: "ResetIpv4Nameservers"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv4Prefix", GoMethod: "ResetIpv4Prefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv4PrefixLength", GoMethod: "ResetIpv4PrefixLength"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv6Gateway", GoMethod: "ResetIpv6Gateway"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv6Nameservers", GoMethod: "ResetIpv6Nameservers"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv6Prefix", GoMethod: "ResetIpv6Prefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv6PrefixLength", GoMethod: "ResetIpv6PrefixLength"},
			_jsii_.MemberMethod{JsiiMethod: "resetLabels", GoMethod: "ResetLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetNameservers", GoMethod: "ResetNameservers"},
			_jsii_.MemberMethod{JsiiMethod: "resetNoIpv4Gateway", GoMethod: "ResetNoIpv4Gateway"},
			_jsii_.MemberMethod{JsiiMethod: "resetNoIpv6Gateway", GoMethod: "ResetNoIpv6Gateway"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRegion", GoMethod: "ResetRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetRouted", GoMethod: "ResetRouted"},
			_jsii_.MemberMethod{JsiiMethod: "resetRoutingTableId", GoMethod: "ResetRoutingTableId"},
			_jsii_.MemberProperty{JsiiProperty: "routed", GoGetter: "Routed"},
			_jsii_.MemberProperty{JsiiProperty: "routedInput", GoGetter: "RoutedInput"},
			_jsii_.MemberProperty{JsiiProperty: "routingTableId", GoGetter: "RoutingTableId"},
			_jsii_.MemberProperty{JsiiProperty: "routingTableIdInput", GoGetter: "RoutingTableIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_Network{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.network.NetworkConfig",
		reflect.TypeOf((*NetworkConfig)(nil)).Elem(),
	)
}
