package logmeinstance

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"stackit.logmeInstance.LogmeInstance",
		reflect.TypeOf((*LogmeInstance)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "cfGuid", GoGetter: "CfGuid"},
			_jsii_.MemberProperty{JsiiProperty: "cfOrganizationGuid", GoGetter: "CfOrganizationGuid"},
			_jsii_.MemberProperty{JsiiProperty: "cfSpaceGuid", GoGetter: "CfSpaceGuid"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dashboardUrl", GoGetter: "DashboardUrl"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "imageUrl", GoGetter: "ImageUrl"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "instanceId", GoGetter: "InstanceId"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "parameters", GoGetter: "Parameters"},
			_jsii_.MemberProperty{JsiiProperty: "parametersInput", GoGetter: "ParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "planId", GoGetter: "PlanId"},
			_jsii_.MemberProperty{JsiiProperty: "planName", GoGetter: "PlanName"},
			_jsii_.MemberProperty{JsiiProperty: "planNameInput", GoGetter: "PlanNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "projectId", GoGetter: "ProjectId"},
			_jsii_.MemberProperty{JsiiProperty: "projectIdInput", GoGetter: "ProjectIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putParameters", GoMethod: "PutParameters"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetParameters", GoMethod: "ResetParameters"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "version", GoGetter: "Version"},
			_jsii_.MemberProperty{JsiiProperty: "versionInput", GoGetter: "VersionInput"},
		},
		func() interface{} {
			j := jsiiProxy_LogmeInstance{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"stackit.logmeInstance.LogmeInstanceConfig",
		reflect.TypeOf((*LogmeInstanceConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"stackit.logmeInstance.LogmeInstanceParameters",
		reflect.TypeOf((*LogmeInstanceParameters)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"stackit.logmeInstance.LogmeInstanceParametersOutputReference",
		reflect.TypeOf((*LogmeInstanceParametersOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "enableMonitoring", GoGetter: "EnableMonitoring"},
			_jsii_.MemberProperty{JsiiProperty: "enableMonitoringInput", GoGetter: "EnableMonitoringInput"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTcp", GoGetter: "FluentdTcp"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTcpInput", GoGetter: "FluentdTcpInput"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTls", GoGetter: "FluentdTls"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsCiphers", GoGetter: "FluentdTlsCiphers"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsCiphersInput", GoGetter: "FluentdTlsCiphersInput"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsInput", GoGetter: "FluentdTlsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsMaxVersion", GoGetter: "FluentdTlsMaxVersion"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsMaxVersionInput", GoGetter: "FluentdTlsMaxVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsMinVersion", GoGetter: "FluentdTlsMinVersion"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsMinVersionInput", GoGetter: "FluentdTlsMinVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsVersion", GoGetter: "FluentdTlsVersion"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdTlsVersionInput", GoGetter: "FluentdTlsVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdUdp", GoGetter: "FluentdUdp"},
			_jsii_.MemberProperty{JsiiProperty: "fluentdUdpInput", GoGetter: "FluentdUdpInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "graphite", GoGetter: "Graphite"},
			_jsii_.MemberProperty{JsiiProperty: "graphiteInput", GoGetter: "GraphiteInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ismDeletionAfter", GoGetter: "IsmDeletionAfter"},
			_jsii_.MemberProperty{JsiiProperty: "ismDeletionAfterInput", GoGetter: "IsmDeletionAfterInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismJitter", GoGetter: "IsmJitter"},
			_jsii_.MemberProperty{JsiiProperty: "ismJitterInput", GoGetter: "IsmJitterInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismJobInterval", GoGetter: "IsmJobInterval"},
			_jsii_.MemberProperty{JsiiProperty: "ismJobIntervalInput", GoGetter: "IsmJobIntervalInput"},
			_jsii_.MemberProperty{JsiiProperty: "javaHeapspace", GoGetter: "JavaHeapspace"},
			_jsii_.MemberProperty{JsiiProperty: "javaHeapspaceInput", GoGetter: "JavaHeapspaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "javaMaxmetaspace", GoGetter: "JavaMaxmetaspace"},
			_jsii_.MemberProperty{JsiiProperty: "javaMaxmetaspaceInput", GoGetter: "JavaMaxmetaspaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxDiskThreshold", GoGetter: "MaxDiskThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "maxDiskThresholdInput", GoGetter: "MaxDiskThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "metricsFrequency", GoGetter: "MetricsFrequency"},
			_jsii_.MemberProperty{JsiiProperty: "metricsFrequencyInput", GoGetter: "MetricsFrequencyInput"},
			_jsii_.MemberProperty{JsiiProperty: "metricsPrefix", GoGetter: "MetricsPrefix"},
			_jsii_.MemberProperty{JsiiProperty: "metricsPrefixInput", GoGetter: "MetricsPrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "monitoringInstanceId", GoGetter: "MonitoringInstanceId"},
			_jsii_.MemberProperty{JsiiProperty: "monitoringInstanceIdInput", GoGetter: "MonitoringInstanceIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "opensearchTlsCiphers", GoGetter: "OpensearchTlsCiphers"},
			_jsii_.MemberProperty{JsiiProperty: "opensearchTlsCiphersInput", GoGetter: "OpensearchTlsCiphersInput"},
			_jsii_.MemberProperty{JsiiProperty: "opensearchTlsProtocols", GoGetter: "OpensearchTlsProtocols"},
			_jsii_.MemberProperty{JsiiProperty: "opensearchTlsProtocolsInput", GoGetter: "OpensearchTlsProtocolsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableMonitoring", GoMethod: "ResetEnableMonitoring"},
			_jsii_.MemberMethod{JsiiMethod: "resetFluentdTcp", GoMethod: "ResetFluentdTcp"},
			_jsii_.MemberMethod{JsiiMethod: "resetFluentdTls", GoMethod: "ResetFluentdTls"},
			_jsii_.MemberMethod{JsiiMethod: "resetFluentdTlsCiphers", GoMethod: "ResetFluentdTlsCiphers"},
			_jsii_.MemberMethod{JsiiMethod: "resetFluentdTlsMaxVersion", GoMethod: "ResetFluentdTlsMaxVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetFluentdTlsMinVersion", GoMethod: "ResetFluentdTlsMinVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetFluentdTlsVersion", GoMethod: "ResetFluentdTlsVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetFluentdUdp", GoMethod: "ResetFluentdUdp"},
			_jsii_.MemberMethod{JsiiMethod: "resetGraphite", GoMethod: "ResetGraphite"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmDeletionAfter", GoMethod: "ResetIsmDeletionAfter"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmJitter", GoMethod: "ResetIsmJitter"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmJobInterval", GoMethod: "ResetIsmJobInterval"},
			_jsii_.MemberMethod{JsiiMethod: "resetJavaHeapspace", GoMethod: "ResetJavaHeapspace"},
			_jsii_.MemberMethod{JsiiMethod: "resetJavaMaxmetaspace", GoMethod: "ResetJavaMaxmetaspace"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxDiskThreshold", GoMethod: "ResetMaxDiskThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetricsFrequency", GoMethod: "ResetMetricsFrequency"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetricsPrefix", GoMethod: "ResetMetricsPrefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetMonitoringInstanceId", GoMethod: "ResetMonitoringInstanceId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOpensearchTlsCiphers", GoMethod: "ResetOpensearchTlsCiphers"},
			_jsii_.MemberMethod{JsiiMethod: "resetOpensearchTlsProtocols", GoMethod: "ResetOpensearchTlsProtocols"},
			_jsii_.MemberMethod{JsiiMethod: "resetSgwAcl", GoMethod: "ResetSgwAcl"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyslog", GoMethod: "ResetSyslog"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "sgwAcl", GoGetter: "SgwAcl"},
			_jsii_.MemberProperty{JsiiProperty: "sgwAclInput", GoGetter: "SgwAclInput"},
			_jsii_.MemberProperty{JsiiProperty: "syslog", GoGetter: "Syslog"},
			_jsii_.MemberProperty{JsiiProperty: "syslogInput", GoGetter: "SyslogInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_LogmeInstanceParametersOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
