package volume


type VolumeEncryptionParameters struct {
	// UUID of the key within the STACKIT-KMS to use for the encryption.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.78.1/docs/resources/volume#kek_key_id Volume#kek_key_id}
	KekKeyId *string `field:"required" json:"kekKeyId" yaml:"kekKeyId"`
	// UUID of the keyring where the key is located within the STACKTI-KMS.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.78.1/docs/resources/volume#kek_keyring_id Volume#kek_keyring_id}
	KekKeyringId *string `field:"required" json:"kekKeyringId" yaml:"kekKeyringId"`
	// Version of the key within the STACKIT-KMS to use for the encryption.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.78.1/docs/resources/volume#kek_key_version Volume#kek_key_version}
	KekKeyVersion *float64 `field:"required" json:"kekKeyVersion" yaml:"kekKeyVersion"`
	// Service-Account linked to the Key within the STACKIT-KMS.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.78.1/docs/resources/volume#service_account Volume#service_account}
	ServiceAccount *string `field:"required" json:"serviceAccount" yaml:"serviceAccount"`
	// Optional predefined secret, which will be encrypted against the key-encryption-key within the STACKIT-KMS.
	//
	// If not defined, a random secret will be generated by the API and encrypted against the STACKIT-KMS. If a key-payload is provided here, it must be base64 encoded.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.78.1/docs/resources/volume#key_payload_base64 Volume#key_payload_base64}
	KeyPayloadBase64 *string `field:"optional" json:"keyPayloadBase64" yaml:"keyPayloadBase64"`
	// Optional predefined secret, which will be encrypted against the key-encryption-key within the STACKIT-KMS.
	//
	// If not defined, a random secret will be generated by the API and encrypted against the STACKIT-KMS. If a key-payload is provided here, it must be base64 encoded.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.78.1/docs/resources/volume#key_payload_base64_wo Volume#key_payload_base64_wo}
	KeyPayloadBase64Wo *string `field:"optional" json:"keyPayloadBase64Wo" yaml:"keyPayloadBase64Wo"`
	// Used together with `key_payload_base64_wo` to trigger an re-create. Increment this value when an update to `key_payload_base64_wo` is required.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stackitcloud/stackit/0.78.1/docs/resources/volume#key_payload_base64_wo_version Volume#key_payload_base64_wo_version}
	KeyPayloadBase64WoVersion *float64 `field:"optional" json:"keyPayloadBase64WoVersion" yaml:"keyPayloadBase64WoVersion"`
}

